dist: xenial
language: python
python: 3.7
services:
- docker
env:
  global:
  - IMAGE_NAME=bksaville/yuri
  - DOCKER_USERNAME=bksaville
  # DOCKER_PASSWORD=...
  - secure: K+iKHPp+30ipoYRSzhaQTclmnSRLxOTaFnE06J7hH4FaFXLsO+YmajrodYVq98o6W6RdazN3tjzSBAnTi+h8jcDovODXb9B5Gi+qzOLPvzG1zXJoKODx083m3xqxHXwDDh8AAa2Qzmm2AW41ZirhpIE12GjkBQl2EDHSyaEunLo+rPjS6hxP7fk9SSf7HFyZQ8Ed7z0MS05S4fIYNYq2eKOfdWP1H2k4WRHBHzJphDgJex2DYzIydSh4I+Q11JNxTi9dCRdpHRRHSvhoxLcl8hdP6dh3iR/4tBJ6uMxDB4G/1PaxyI8mJsLwjhUjti6Azb5y5rWmY95yWbCwXIGgfuBcwKYeV8TpI/8PvGeucXxb8hXeiSX3zDKPmC/eMjPAqGcHJ25FzK9ffxSdL8yIpaQBpgiroA2xTZmd2a7JLlDCdmyZg2qUK4iiUG0H/dwuRJTOkJkp3ixV+6i7Jykk54DUYd+jlUmde6Q3uwJLMhnxIsgoRqcLHn/G1n31GnPc/T1oL1dnoRqUfnK7D/z5uiiufhdlU6+zkCE7OI1sCUmkUZsuSmljt4kSCM6tXj9DbDnBFKlrC1fSIq/SVDqD2QKAPIWRQ/an/Ki5n7jVS94lpXQfh/+izMcD9lvlAasRjaP1WwEFg2pE189P9ojE1n9n0ofvmu5ZUJ2ObYVBFn8=
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install: pip install tox
script:
- |
  if [[ $TRAVIS_TAG == "" ]]; then
    tox
  fi
deploy:
#- provider: pypi
#  distributions: sdist bdist_wheel
#  user: __token__
#  password:
#    secure: <ENCRYPTED-PASSWORD>
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: bluesliverx/yuri
- provider: script
  script: bash deploy-docker
  on:
    tags: true
