dist: xenial
language: python
python: 3.7
services:
- docker
env:
  global:
  - IMAGE_NAME=bksaville/yuri
  - DOCKER_USERNAME=bksaville
  # DOCKER_PASSWORD=...
  - secure: "JgP1KZL87MNAzxTcCXEx5FmDIiYsluGEbXx8dbrXUKMYtpRCGOpxOJCE9MAmCqL661h7UP1IMEl036t1kyc0tiWJ3rIJBUn7IzdeNoLt/s//WrwrsxwizOaOW5LtIzW/jcAcxlJY54VT9GvfNGVKLf/16Jrj1UeAEOv+umkPzGxFV7xMdzV8JXpc5m+JwkvdwlZthimoZ6j9YgpmbIejz3jygnH3GZgzHpq1yIQvG9F2O/vR1PRyf+gJ3DT7iRffk2HsNa9xk3HvF+cQRvDjLw6nwyRvebTI4DyajsddRJuaYMbhFJgYwV94EX8sMxrddH2igXtbeJ7mk7R1Cvvc6YPQcpEzOmA9FUHstAlAL5l/b6dzBbTbC1aTE0jbOGxYYmWgPsYMgiGVipeM3f4qO1GvWMoNVMDaPFba35vOzhHRDDxBvspkLz89zchZBX+L8ND6bpZl553U61qQSv9XoEVqdntn02CpN6t9JI5Y6oBd3MCl5yPVqSzAwoWbtnWVM5VvheRqkLmCeeL41JQqzvT2QQ3prFPihMMufT3upcqjpGEWjct0T/Nvr3kHbCC4OBeQJ+73W1vPnqFZ8ZkSmPtf8Fh2yBFhlG2rjog853OvWPDI+Khr+GX651OxOvmF6KmDnErOLB8A8VHE3wzCZIeKjFYhpM41RbJc1bUVq40="
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install: pip install tox
script:
- |
  if [[ $TRAVIS_TAG == "" ]]; then
    tox
  fi
deploy:
#- provider: pypi
#  distributions: sdist bdist_wheel
#  user: __token__
#  password:
#    secure: <ENCRYPTED-PASSWORD>
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: bluesliverx/yuri
- provider: script
  script: bash deploy-docker
  on:
    tags: true
