dist: xenial
language: python
python: 3.7
services:
- docker
env:
  global:
  - IMAGE_NAME=bksaville/yuri
  - DOCKER_USERNAME=bksaville
  # DOCKER_PASSWORD=...
  - secure: "Gy5OWDjfMlAi0jTUZlIQHZyiOnOLLtVcFk3TjPBNTitZyBOK+DFzC8pK/QEcPXXUPahNugjuuOVAjU7P2xz6iHRfxesacdwHlfNVr0+evmZGj+/6XsWoPsM6pTCE5iwoKfBKobLznUIs0MyIJoId9aOwcd/xJNjn0g7uUbGmEUu3ljSqb+Bty7RBpsS8ChX1s2hNAdmRO+U5lhiN1SrBzHL6JRtdGeO1zWbAAq+sc32yed02kaSbf6yZhtPbcp1HKsrHP81FXQOJ+eYoxjqPqYvx9XIA0aYpNNB6Buix3IgXKNOOmNc0C+2FCfnLS+QscSkxavy6lsIzZ1z5jNwbg6grPaAOZbSM9fq7eTSRWu8Srup320bQrnAbxgezzUOq8wP9ZF2dM/u7KBEpS35bf1u4fiMU0S81Z9KrdVdIe3P0ipQ99e7RpZwLvi6T+sQUbhIcJNCC2rdrPVZ68v9X02TBCbnS2/UXyq/dYcRnU7kkELdoPsK2ULCN7O6ZWtV+hQSrUcnsybCMw3m1Ze0NPT7ayE6+NrDdTwoRmU4PBrrXylhThc24S78IaBYiVhyJ7/FHAW1s5a/I2B2kfg3rmwJmmPOCj9QA5jyaC6pqTBSQLG1dZtg+yHsneYYCnuzKWx96IHk0dHyxSYav8Jt5EirSHUQXgvjEIsfLGk1sZug="
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install: pip install tox
script:
- |
  if [[ $TRAVIS_TAG == "" ]]; then
    tox
  fi
deploy:
#- provider: pypi
#  distributions: sdist bdist_wheel
#  user: __token__
#  password:
#    secure: <ENCRYPTED-PASSWORD>
#  skip_cleanup: true
#  on:
#    tags: true
#    repo: bluesliverx/yuri
- provider: script
  script: bash deploy-docker
  on:
    tags: true
