#!/bin/bash
# This is meant to be used from travis only
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "Building base docker image..."
docker build -t $BASE_IMAGE_NAME-base:latest .
echo "Building bot image..."
docker build -t $BASE_IMAGE_NAME-bot:latest --build-arg FROM_IMAGE=$BASE_IMAGE_NAME-base -f Dockerfile-bot .
echo "Build yuri image..."
docker build -t $BASE_IMAGE_NAME-yuri:latest --build-arg FROM_IMAGE=$BASE_IMAGE_NAME-base -f Dockerfile-yuri .

if [[ $TRAVIS_TAG == "" ]]; then
    echo "Not a tagged build, skipping push"
else
    echo "Pushing images..."
    docker tag $BASE_IMAGE_NAME-bot:latest $BASE_IMAGE_NAME-bot:$TRAVIS_TAG
    docker tag $BASE_IMAGE_NAME-yuri:latest $BASE_IMAGE_NAME-yuri:$TRAVIS_TAG
    docker push $BASE_IMAGE_NAME-bot:latest
    docker push $BASE_IMAGE_NAME-yuri:latest
    docker push $BASE_IMAGE_NAME-bot:$TRAVIS_TAG
    docker push $BASE_IMAGE_NAME-yuri:$TRAVIS_TAG
fi
