#!/bin/bash
# This is meant to be used from travis only
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t $IMAGE_NAME:latest .

if [[ $TRAVIS_TAG == "" ]]; then
    echo "Not a tagged build, skipping push"
else
    echo "Pushing images..."
    docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TRAVIS_TAG
    docker push $IMAGE_NAME:latest
    docker push $IMAGE_NAME:$TRAVIS_TAG
fi
